export const adminDashboardContent = {
  banner: {
    kicker: "Admin control",
    title: "لوحة الإدارة الرئيسية",
    description:
      "رؤية مركزية لإدارة الشركات، المدفوعات، الأداء، وحالة التشغيل اليومية عبر جميع شركات البالون داخل المنصة.",
    chips: ["32 شركة مستهدفة", "8 قنوات بيع", "4 مسارات تشغيل"],
  },
  kpis: [
    {
      label: "الحجوزات المؤكدة اليوم",
      value: "412",
      trend: "+12% مقارنة بأمس",
      tone: "success",
    },
    {
      label: "إيراد متوقع",
      value: "$34.8k",
      trend: "يشمل B2B وB2C",
      tone: "warning",
    },
    {
      label: "شركات نشطة",
      value: "29 / 32",
      trend: "3 شركات بانتظار الاستكمال",
      tone: "neutral",
    },
    {
      label: "مدفوعات تحتاج مراجعة",
      value: "11",
      trend: "7 تحويلات و4 بطاقات",
      tone: "danger",
    },
  ],
  companyRows: [
    {
      id: "nile-sunrise",
      company: "Nile Sunrise Balloons",
      manager: "عمر عبد الرحمن",
      occupancy: "91%",
      seats: "82 / 90",
      revenue: "$6.4k",
      payout: "$4.9k",
      status: "مستقرة",
      tone: "success",
      note: "طلب قوي على رحلات الفجر",
    },
    {
      id: "golden-sky",
      company: "Golden Sky Balloons",
      manager: "سارة فتحي",
      occupancy: "84%",
      seats: "63 / 75",
      revenue: "$5.1k",
      payout: "$3.8k",
      status: "تحتاج متابعة",
      tone: "warning",
      note: "تعديل سعات على الرحلة الثانية",
    },
    {
      id: "pharaoh-air",
      company: "Pharaoh Air Tours",
      manager: "ندى يوسف",
      occupancy: "76%",
      seats: "38 / 50",
      revenue: "$3.2k",
      payout: "$2.4k",
      status: "قيد اعتماد",
      tone: "neutral",
      note: "ربط الدفع لم يكتمل بعد",
    },
    {
      id: "desert-crown",
      company: "Desert Crown Balloons",
      manager: "كريم عادل",
      occupancy: "68%",
      seats: "34 / 50",
      revenue: "$2.7k",
      payout: "$2.1k",
      status: "مخاطرة تشغيلية",
      tone: "danger",
      note: "3 إلغاءات بسبب تحديث الطقس",
    },
  ],
  channelMix: [
    { label: "الحجز المباشر B2C", value: "44%", progress: 44 },
    { label: "الوكالات والشركاء B2B", value: "38%", progress: 38 },
    { label: "OTA / قنوات خارجية", value: "12%", progress: 12 },
    { label: "حجوزات تعاقدية", value: "6%", progress: 6 },
  ],
  approvals: [
    {
      title: "3 شركات تنتظر اعتماد نهائي",
      detail: "استكمال مستندات التشغيل وربط وسيلة الدفع قبل فتح المبيعات.",
      tone: "warning",
    },
    {
      title: "11 دفعة تحتاج تسوية",
      detail: "مطابقة أرقام المراجع البنكية مع حجوزات اليوم.",
      tone: "danger",
    },
    {
      title: "5 وكالات جديدة تطلب أسعارًا تعاقدية",
      detail: "إنشاء شرائح B2B وربطها بالشركات المعنية.",
      tone: "neutral",
    },
  ],
  integrations: [
    {
      name: "بوابة الدفع الرئيسية",
      status: "متصلة",
      tone: "success",
      detail: "آخر مزامنة منذ 6 دقائق",
    },
    {
      name: "قناة Shopify التجريبية",
      status: "قيد التجهيز",
      tone: "warning",
      detail: "ينقص ربط منتجات الرحلات",
    },
    {
      name: "تكامل التذاكر السياحية",
      status: "على خارطة الطريق",
      tone: "neutral",
      detail: "المعابد والأتوبيسات وعروض الصوت والضوء",
    },
    {
      name: "ربط Booking.com / Amadeus",
      status: "تحليل تقني",
      tone: "neutral",
      detail: "يتطلب تصميم API وتعاقدات القنوات",
    },
  ],
  alerts: [
    "شركة Desert Crown سجلت نسبة إلغاء أعلى من المتوسط خلال آخر 24 ساعة.",
    "هناك رحلتان ممتلئتان بالكامل وتحتاجان مراجعة حدود السعة قبل فتح حجوزات إضافية.",
    "تقرير التسويات المالية لثلاث شركات لم يُقفل حتى الآن.",
  ],
  checklist: [
    "اعتماد الشركات الجديدة قبل الساعة 11:00 مساءً.",
    "مراجعة أسعار الوكالات الأعلى مبيعًا وتحديث العقود.",
    "إغلاق حالات الدفع المعلقة قبل الترحيل المالي اليومي.",
    "مراجعة الشركات ذات الإشغال الأقل من 70% ووضع خطة توزيع أفضل.",
  ],
};

export function getOperatorDashboardContent(organizationName) {
  return {
    banner: {
      kicker: "Operator workspace",
      title: "لوحة تشغيل الشركة",
      description: `مساحة ${organizationName} لإدارة الرحلات اليومية، السعات، الحجوزات، التسعير، والوكلاء المرتبطين بالشركة.`,
      chips: ["6 رحلات فجر", "84% إشغال عام", "63 فاوتشر جاهز"],
    },
    kpis: [
      {
        label: "رحلات اليوم",
        value: "6",
        trend: "4 فجر + 2 جولة خاصة",
        tone: "neutral",
      },
      {
        label: "إشغال المقاعد",
        value: "84%",
        trend: "63 مقعدًا مؤكدًا",
        tone: "success",
      },
      {
        label: "حجوزات B2B",
        value: "47",
        trend: "أعلى قناة مبيعًا اليوم",
        tone: "warning",
      },
      {
        label: "طلبات تحتاج تدخل",
        value: "8",
        trend: "تعديل أسماء / تحويلات / إلغاء",
        tone: "danger",
      },
    ],
    flights: [
      {
        id: "sunrise-1",
        trip: "رحلة الفجر 01",
        departure: "04:45",
        capacity: "16 / 18",
        mix: "10 B2B / 6 B2C",
        guide: "محمد علي",
        status: "جاهزة",
        tone: "success",
      },
      {
        id: "sunrise-2",
        trip: "رحلة الفجر 02",
        departure: "05:05",
        capacity: "14 / 18",
        mix: "8 B2B / 6 B2C",
        guide: "أحمد شوقي",
        status: "تحتاج مراجعة",
        tone: "warning",
      },
      {
        id: "sunrise-3",
        trip: "رحلة الفجر 03",
        departure: "05:20",
        capacity: "11 / 18",
        mix: "7 B2B / 4 B2C",
        guide: "أمل سعد",
        status: "مفتوحة",
        tone: "neutral",
      },
      {
        id: "charter-1",
        trip: "رحلة خاصة",
        departure: "06:15",
        capacity: "6 / 8",
        mix: "2 B2B / 4 B2C",
        guide: "نور خالد",
        status: "VIP",
        tone: "success",
      },
    ],
    pricing: [
      {
        channel: "B2C",
        amount: "$100",
        note: "البيع المباشر عبر الموقع",
      },
      {
        channel: "B2B",
        amount: "$80",
        note: "أسعار الشركاء والوكالات",
      },
      {
        channel: "OTA",
        amount: "$92",
        note: "قنوات التوزيع الخارجية",
      },
    ],
    partnerRows: [
      {
        id: "pharaoh-travel",
        agency: "Pharaoh Travel",
        bookings: "12",
        balance: "$1.8k",
        credit: "$3k",
        status: "نشطة",
        tone: "success",
        note: "آخر حجز منذ 18 دقيقة",
      },
      {
        id: "desert-gate",
        agency: "Desert Gate",
        bookings: "9",
        balance: "$620",
        credit: "$1.5k",
        status: "تحتاج متابعة",
        tone: "warning",
        note: "دفعتان بانتظار التأكيد",
      },
      {
        id: "lotus-holidays",
        agency: "Lotus Holidays",
        bookings: "4",
        balance: "$0",
        credit: "$1k",
        status: "موقوفة مؤقتًا",
        tone: "danger",
        note: "تجاوزت الحد الائتماني",
      },
    ],
    bookingMix: [
      { label: "B2B", value: "56%", progress: 56 },
      { label: "B2C", value: "31%", progress: 31 },
      { label: "OTA", value: "13%", progress: 13 },
    ],
    actions: [
      "تأكيد الأسماء النهائية للركاب قبل طباعة كشف الرحلات.",
      "مراجعة طلبات الأطفال والرضع لضبط حمولة كل رحلة.",
      "متابعة الحالات التي تحتاج إعادة إرسال الفاوتشر أو تعديل وقت التحرك.",
      "إقفال الرحلات الممتلئة ومنع الحجز الزائد قبل منتصف الليل.",
    ],
    guestAlerts: [
      {
        title: "3 ضيوف يطلبون تعديل نقطة الالتقاء",
        detail: "يلزم إعادة إصدار الفاوتشر برسالة واتساب محدثة.",
        tone: "warning",
      },
      {
        title: "طلب إلغاء واحد من وكالة Lotus Holidays",
        detail: "الحجز تجاوز حد الائتمان ويحتاج قرارًا ماليًا.",
        tone: "danger",
      },
      {
        title: "8 فاوتشرات لم تُحمّل بعد",
        detail: "يمكن إعادة إرسالها مباشرة بعد التحقق من البريد.",
        tone: "neutral",
      },
    ],
  };
}
